### ISSUE TITLE
BIP-32 based EOTS randomness derivation/timestamping

### ISSUE THREAD

**Issue by SebastianElvis** [babylonchain/babylon#591]
Proposal: https://babylon-chain.atlassian.net/wiki/spaces/BABYLON/pages/214630413/EOTS+randomness+derivation+protocol+from+BIP-32

Steps for implementation:

- Babylon side
  - [x] master secret/public randomness, DB schema, and message formats (#594 )
  - [x] Removing `MsgCommitPubRandList` and using master public randomness for verifying finality signatures (#595 )
  - [x] BTC timestamping master public randomness for finality providers (#598 )
  - [x] Docs and changelogs (#604 )
- Finality provider side
  - [x] master secret/public randomness, DB schema, and message formats in EOTS manager
  - [x] master secret/public randomness, DB schema, and message formats in finality provider
  - [x] Removing `MsgCommitPubRandList` and using master public randomness for verifying finality signatures
  - [x] BTC timestamping master public randomness for finality providers
  - [x] Docs and changelogs
- [ ] Bump vigilantes
